### ISSUE TITLE
Imperial Shuttle Wipes Plan

### ISSUE THREAD

**Issue by mthomas768** [Scherub/rw-planning-extended#98]
I had a shuttle land on a plan I was working on. The shuttle wiped out the plan area beneath it. Not a huge deal, obviously. It was more entertaining than anything. You can see from the screenshot the wiped-out area.

![Screenshot_41](https://user-images.githubusercontent.com/25303992/235312194-f03b77a3-1920-44a6-8f08-ae5d57020fca.jpg)

**Comment by Scherub** [comment]
Curious, that the shuttle even removes the designations. Do you have 'persistent plans' enabled in the settings?

**Comment by mthomas768** [comment]
I do not. I'm guessing the shuttle landing is counting as "something built on this spot", and that is blanking the plan area within the shuttle footprint.

**Comment by Scherub** [comment]
I think you're right. When a shuttle lands, it destroys most things on these cells. And it makes sense if it removes designations such as 'Harvest' or 'Cut', as farm field tiles are also destroyed. Therefore, it will probably just remove any designations without checking whether it's necessary.

Unfortunately, I don't think there is much I can do here. The only thing you could try is using the setting 'persistent plans'.
